version: '3'

services:
  front-end:
    image: skychang/crud-blazor-front-serverside:3.0.0-preview5
    container_name: front-end
    build:
      context: ./CrudBlazor.FrontServerSite
      dockerfile: Dockerfile
      #args:
      #    source: bin/Debug/netcoreapp3.0/publish 
    environment:
      - ASPNETCORE_ENVIRONMENT=DevTest
    ports:
      - "4000:80"
      - "4001:443"

  web-api:
    image: skychang/crud-aspnetcore:3.0.0-preview5
    container_name: web-api
    environment:
      - ASPNETCORE_ENVIRONMENT=DevTest
    depends_on: 
        - sqlserver
    ports:
      - "5000:80"
      - "5001:443"
          
  sqlserver:
    image: microsoft/mssql-server-linux
    container_name: sqlserver
    ports: 
        - "1433:1433"
    environment: 
        SA_PASSWORD: P@ssw0rd
        ACCEPT_EULA: Y
        #attach_dbs: "[{'dbName':'trunk','dbFiles':['c:\\\\Databases\\\\trunk.mdf','c:\\\\Databases\\\\trunk_Log.ldf']}]"
    healthcheck:
      test: "exit 0"