apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
  - name: frontend-public-port
    port: 80
    targetPort: frontend-port
  type: LoadBalancer
  selector:
    app: frontend